version: '3.8'

services:
  onebox:
    build:
      context: ..
      dockerfile: u22/Dockerfile
      target: onebox
    privileged: true
    ports:
      - "19080:19080"
      - "19000:19000"
  repo-u22:
    build:
      context: ..
      dockerfile: u22/Dockerfile
      target: repo
    volumes:
      - ../../:/workspaces/repo # repo dir
      - ~/.ssh:/root/.ssh:ro # git creds
      - /tmp/artifacts/coredumps:/tmp/artifacts/coredumps # core dumps
    depends_on:
      - onebox
    
  
