// Bindings generated by `windows-bindgen` 0.58.0

#[cfg(feature = "ServiceFabric_FabricClient")]
pub mod FabricClient;
#[cfg(feature = "ServiceFabric_FabricCommon")]
pub mod FabricCommon;
#[cfg(feature = "ServiceFabric_FabricRuntime")]
pub mod FabricRuntime;
#[cfg(feature = "ServiceFabric_FabricTransport")]
pub mod FabricTransport;
#[cfg(feature = "ServiceFabric_FabricTypes")]
pub mod FabricTypes;
